projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('list/', views.ProjectListView.as_view(), name='project-list'),
    path('<slug:slug>', views.ProjectDetailView.as_view(), name='project-detail'),
]

skills/urls.py
from django.urls import path

from . import views

app_name = 'skills'

urlpatterns = [
    path('list/', views.SkillListView.as_view(), name='skill-list'),
    ]

talent_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from talent_portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('skills/', include('skills.urls')),
    path('', views.IndexTemplateView.as_view(), name='index'),
]

projects/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Project(models.Model):

    creation_date = models.DateField(auto_now=True)
    publication_date = models.DateField(blank=True, null=True)
    active = models.BooleanField(default=False)
    project_title = models.CharField(max_length=250)
    project_description = models.TextField(blank=True)
    project_url = models.URLField(blank=True, null=True)
    last_viewed = models.DateTimeField()
    slug = models.SlugField()

    def __str__(self):
        return self.project_title

    def get_absolute_url(self):
        return reverse('projects:project-detail', kwargs={"slug": self.slug, })

skills/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Skill(models.Model):
    """Class for individual skills."""

    skill_name = models.CharField(max_length=100)
    skill_level = models.TextField(blank=True)
    skill_category = models.ForeignKey('SkillCategory', on_delete=models.CASCADE)
    slug = models.SlugField()

    def __str__(self):
        return self.skill_name


class SkillCategory(models.Model):
    """Class for skill categories, grouping skills."""

    category_name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = 'SkillCategories'

    def __str__(self):
        return self.category_name

projects/views.py
from django.views.generic import ListView, DetailView

from . models import Project


class ProjectListView(ListView):
    template_name = 'projects/project_list.html'
    context_object_name = 'projects'
    queryset = Project.objects.filter(active=True).order_by('project_title')


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'projects/project_detail.html'

skills/views.py
from django.views.generic import ListView, DetailView

from . models import Skill


class SkillListView(ListView):
    template_name = 'skills/skill_list.html'
    context_object_name = 'skills'
    queryset = Skill.objects.all().order_by('-skill_name')

talent_portfolio/views.py
from django.views.generic import TemplateView


class IndexTemplateView(TemplateView):
    template_name = 'index.html'

projects/templates/projects/project_detail.html
{% extends "base.html" %}

{% block content %}
  <p>
    <h1 class="text-muted">{{ project.project_title }}</h1>
  </p><br>
  <p>{{ project.project_description }}</p>
  <p>Sourcecode Here <a href="{{ project.project_url }}">{{ project.project_url }}</a></p>
{% endblock %}

projects/templates/projects/project_list.html
{% extends "base.html" %}

{% block content %}
  <p>
    <h2 class="text-muted">List of projects</h2>
  </p><br>
      {% for project in projects %}
          <p><a href="{% url 'projects:project-detail' project.slug %}">{{ project.project_title }}</a></p>
      {% endfor %}
{% endblock %}

skills/templates/skills/skill_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ skill.skill_name }}</h1>
  <p>{{ skill.skill_category }}</p>
{% endblock %}

skills/templates/skills/skill_list.html
{% extends "base.html" %}

{% block content %}
  <h2 class="text-muted">My Skills</h2><br>
  <p>
  <div class="card-group">
    {% for skill in skills %}
    <div class="card">
      <div class="card-header">
      <medium class="text-muted">{{ skill.skill_name }}</small>
    </div>
      <div class="card-body">
        <h4 class="card-title"></h4>
        <b><p class="card-text text-muted">{{ skill.skill_category }}</p></b>
        <p class="card-text">Level: {{ skill.skill_level }}</p>
    </div>
    </div>
    {% endfor %}
  </div>
  </p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Portfolio Site{% endblock %}</title>
  </head>
  <link rel="stylesheet" href="{% static 'images/tt.png' %}">
  <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/css/narrow-jumbotron.css' %}" type="text/css">
  <body>
    <div class="container">
      <header class="header clearfix">
       <nav>
         <ul class="nav nav-pills float-right">
           <li class="nav-item">
             <a class="nav-link text-muted" href="{% url 'index' %}">Home</a>
           </li>
           <li class="nav-item">
             <a class="nav-link text-muted" href="{% url 'projects:project-list' %}">Portfolio</a>
           </li>
           <li class="nav-item">
             <a class="nav-link text-muted" href="{% url 'skills:skill-list' %}">Skills</a>
           </li>
         </ul>
       </nav>
       <h3 ><a class="text-muted" href="{% url 'index' %}">Portfolio Website</a></h3>
     </header>

     <main role="main">
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </main><br><br>
    <div class="container">
      <h2 class="text-muted">Contact Details</h2>
      <footer class="footer">
        <div class="row">
          <div class="col-md-4">
            <h4>Email Address: </h4>
            <a href="mailto:talentmabuto3@gmail.com">talentmabuto3@gmail.com</a>
          </div>
          <div class="col-md-4">
            <h4>Address</h4>
            1238 Southlea Park <br>
            Harare, Zimbabwe <br>
          </div>
          <div class="col-md-4">
            <h4>Mobile Number</h4>
            <p>+263774579680</p>
          </div>
        </div><br><br>
        <p>Talent Mabuto &copy; {% now 'Y' %} Portfolio Website</p>
      </footer>
    </div>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
     <h1 class="display-3">Talent Mabuto</h1>
       <h2 class="text-muted">Web Developer</h2>
     <p class="lead">This is my personal portfolio website, that stipulate my experience and skills as a Web Developer</p>
   </div>
</div>
{% endblock %}